# trigger build
version: 2
debug: true
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: "Installing Dependencies"
          command: "sudo pip3 install -r requirements.txt"
      - run:
          name: "Running the Unit Tests"
          command: "coverage run tests/sanity.py"
      - run:
          name: "Sending coverage reports to CodeCov"
          command: "bash <(curl -s https://codecov.io/bash)"

  build-docs:
      docker:
      - image: circleci/python:3.7.3
      steps:
      - checkout
      - run:
          name: "Installing Dependencies"
          command: "sudo pip3 install -r requirements.txt"
      - run:
          name: "Setting environment variable"
          command: "export PYTHONWARNINGS='error::UserWarning'"
      - run:
          name: "Building documenation using pdoc3"
          command: "pdoc --html --skip-errors --output-dir docs ."
      - run:
          name: "cd into docs"
          command: "cd docs && pwd && cd $(ls) && pwd && ls && cd src && ls && pwd"
      - run:
          name: "print git creds"
          command: "git config --list"
      - persist_to_workspace:
          root: ~/project/docs
          paths: project

  docs-deploy:
      docker:
      - image: node:8.10.0
      steps:
      - checkout
      - attach_workspace:
            at: ~/project/docs/project
      - run:
            name: "which dir"
            command: "ls && pwd"
      - run:
            name: Install and configure dependencies
            command: |
                npm install -g --silent gh-pages@2.0.1
      - run:
            name: Deploy docs to gh-pages branch
            command: gh-pages --dist docs/project

workflows:
  version: 2
  test:
    jobs:
      - test
      - build-docs
      - docs-deploy:
          requires:
            - test
            - build-docs
